SELECT * FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST";

--Removing ~ from data

UPDATE "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
SET FDGRP_CD = REPLACE(FDGRP_CD,'~')

UPDATE "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
SET FDGRP_DESC = REPLACE(FDGRP_DESC,'~')

-- Resetting the data

UPDATE "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
SET FDGRP_CD = '~'||FDGRP_CD||'~'

UPDATE "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
SET FDGRP_DESC = '~'||FDGRP_DESC||'~'
