-- create table
CREATE TABLE WEIGHT_INGEST (
    NDB_NO	VARCHAR(7)
    ,SEQ	VARCHAR(4)
    ,AMOUNT	NUMBER(6,3)
    ,MSRE_DESC	VARCHAR(86)
    ,GM_WGT	NUMBER(7,1)
    ,NUM_DATA_PTS	NUMBER(4,0)
    ,STD_DEV	NUMBER(7,3)
  )
 
-- create file format
CREATE FILE FORMAT USDA_FILE_FORMAT 
TYPE = 'CSV' 
COMPRESSION = 'AUTO' 
FIELD_DELIMITER = '^' 
RECORD_DELIMITER = '\n' 
SKIP_HEADER = 0 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
TRIM_SPACE = FALSE 
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' 
TIMESTAMP_FORMAT = 'AUTO' 
NULL_IF = ('\\N');
 

TRUNCATE TABLE WEIGHT_INGEST;
 
-- copy data
COPY INTO WEIGHT_INGEST
FROM @MY_S3_BUCKET/load/
FILES = ('WEIGHT.txt')
FILE_FORMAT = ( FORMAT_NAME='USDA_FILE_FORMAT' )

SELECT COUNT(NDB_NO) FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."WEIGHT_INGEST";

CREATE OR REPLACE TABLE WEIGHT (
    NDB_NO	VARCHAR(5)
    ,SEQ	VARCHAR(2)
    ,AMOUNT	NUMBER(6,3)
    ,MSRE_DESC	VARCHAR(84)
    ,GM_WGT	NUMBER(7,1)
    ,NUM_DATA_PTS	NUMBER(4,0)
    ,STD_DEV	NUMBER(7,3)
  );
  
--ETL to move WEIGHT data from WEIGHT_INGEST to WEIGHT
--LOAD STEP
INSERT INTO WEIGHT(
SELECT 
  --TRANSFORM STEP
    REPLACE(NDB_NO,'~') as NDB_NO
    ,REPLACE(SEQ,'~') as SEQ
    ,AMOUNT
    ,REPLACE(MSRE_DESC,'~') as MSRE_DESC
    ,GM_WGT
    ,NUM_DATA_PTS
    ,STD_DEV
--EXTRACT STEP 
FROM WEIGHT_INGEST);

SELECT * FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."WEIGHT";
SELECT COUNT(NDB_NO) FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."WEIGHT";
